const seed=[
{name:'Maya Chen',role:'Infrastructure strategy operator',topics:['ai infrastructure','data centers','southeast asia','procurement','cloud','energy'],evidence:['12 years in regional infrastructure strategy','Recent data-center procurement work','Frequent executive speaker'],dub:1},
{name:'Jonas Berg',role:'Football commercial executive',topics:['soccer','football','canada','sports business','sponsorship','clubs'],evidence:['Club-side commercial leadership','North American football market experience','Public speaking history'],dub:.5},
{name:'Amina Patel',role:'Biotech researcher and founder',topics:['stem cells','biotech','life sciences','research commercialization','healthcare'],evidence:['Peer-reviewed research background','Founder/operator experience','Translates technical topics for general audiences'],dub:2},
{name:'Marcus Reed',role:'Digital assets infrastructure operator',topics:['crypto','solana','distributed systems','payments','web3','ai agents'],evidence:['Production infrastructure experience','Agent/payment systems focus','Conference speaker'],dub:1},
{name:'Elena Ruiz',role:'Nonprofit growth and governance advisor',topics:['nonprofit','governance','fundraising','community','social impact'],evidence:['15 years nonprofit leadership','Board governance experience','International program delivery'],dub:.5},
{name:'Noah Williams',role:'Sports journalist and analyst',topics:['soccer','football','international soccer','media','canada','world cup'],evidence:['International football coverage','Broadcast experience','Current North American focus'],dub:.25}
];
const $=s=>document.querySelector(s);
const tokenize=v=>new Set(v.toLowerCase().replace(/[^a-z0-9\s]/g,' ').split(/\s+/).filter(x=>x.length>2));
function score(p,q){const a=tokenize(q),b=tokenize([p.role,...p.topics,...p.evidence].join(' '));let hits=0;a.forEach(t=>{if(b.has(t)||[...b].some(x=>x.includes(t)||t.includes(x)))hits++});return Math.max(48,Math.min(96,52+hits*9+p.evidence.length*3));}
function find(){const brief=$('#brief').value.trim();if(!brief)return;const q=`${brief} ${$('#intent').value} ${$('#context').value}`;const list=seed.map(p=>({...p,score:score(p,q)})).sort((a,b)=>b.score-a.score);$('#count').textContent=list.length;$('#strong').textContent=list.filter(p=>p.score>=70).length;$('#results').innerHTML=list.map((p,i)=>`<article class="card peep"><div class="top"><div><h3>${p.name}</h3><small>${p.role}</small></div><b>${p.score}%</b></div><p>${p.evidence.slice(0,2).join(' · ')}</p><div class="crumbs">${p.topics.slice(0,4).map(t=>`<span>${t}</span>`).join('')}</div><footer><button data-dub="${i}">Ask Dub · $${p.dub.toFixed(2)}</button><button class="secondary">Start a Jam</button></footer></article>`).join('');$('#resultsWrap').hidden=false;document.querySelectorAll('[data-dub]').forEach(b=>b.onclick=()=>openDub(list[+b.dataset.dub]));}
function openDub(p){$('#dubBody').innerHTML=`<small>DUB SCREENING · $${p.dub.toFixed(2)} USDC</small><h2>${p.name}</h2><p><b>${p.score}% demonstrated relevance</b> · ${p.role}</p>${p.evidence.map(e=>`<div class="answer"><b>Supported</b><p>${e}</p></div>`).join('')}<div class="answer unknown"><b>Unknown stays unknown</b><p>Anything outside approved evidence should be escalated to the human rather than invented by the Dub.</p></div><button>Spend Dough & ask this Dub</button>`;$('#dub').showModal();}
$('#find').onclick=find;$('#close').onclick=()=>$('#dub').close();